-- MySQL Script generated by MySQL Workbench
-- 07/27/17 16:40:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ictm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ictm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ictm` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ictm` ;

-- -----------------------------------------------------
-- Table `ictm`.`ictmPage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictm`.`ictmPage` (
  `pageId` INT NOT NULL COMMENT '' AUTO_INCREMENT,
  `pageTitle` VARCHAR(255) NOT NULL COMMENT '',
  `pageKeywords` VARCHAR(255) NULL COMMENT '',
  `pageMetaData` VARCHAR(255) NULL COMMENT '',
  `pageType` VARCHAR(45) NULL COMMENT '',
  `pageContent` LONGTEXT NULL COMMENT '',
  `pageImage` VARCHAR(255) NULL COMMENT '',
  `insertedBy` INT NULL COMMENT '',
  `insertedDate` DATETIME NULL COMMENT '',
  `lastModifiedBy` INT NULL COMMENT '',
  `lastModifiedDate` DATETIME NULL COMMENT '',
  `pageStatus` VARCHAR(100) NULL COMMENT '',
  `approvedBy` VARCHAR(100) NULL COMMENT '',
  `publishingDate` DATETIME NULL COMMENT '',
  PRIMARY KEY (`pageId`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictm`.`ictmMenu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictm`.`ictmMenu` (
  `menuId` INT NOT NULL COMMENT '' AUTO_INCREMENT,
  `parentId` INT NULL COMMENT '',
  `pageId` INT NOT NULL COMMENT '',
  `menuName` VARCHAR(100) NOT NULL COMMENT '',
  `menuType` VARCHAR(45) NULL COMMENT '',
  `insertedBy` INT NULL COMMENT '',
  `insertedDate` DATETIME NULL COMMENT '',
  `lastModifiedBy` INT NULL COMMENT '',
  `lastModifiedDate` DATETIME NULL COMMENT '',
  `menuStatus` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`menuId`)  ,
  INDEX `fk_ictmMenu_ictmPage_idx` (`pageId` ASC)  ,
  CONSTRAINT `fk_ictmMenu_ictmPage`
    FOREIGN KEY (`pageId`)
    REFERENCES `ictm`.`ictmPage` (`pageId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictm`.`ictmPageSection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictm`.`ictmPageSection` (
  `pageSectionId` INT NOT NULL COMMENT '' AUTO_INCREMENT,
  `pageId` INT NOT NULL COMMENT '',
  `pageSectionTitle` VARCHAR(255) NULL COMMENT '',
  `pageSectionContent` LONGTEXT NULL COMMENT '',
  `pageSectionImage` VARCHAR(255) NULL COMMENT '',
  `insertedBy` VARCHAR(255) NULL COMMENT '',
  `insertedDate` DATETIME NULL COMMENT '',
  `lastModifiedBy` INT NULL COMMENT '',
  `lastModifiedDate` DATETIME NULL COMMENT '',
  `pageSectionStatus` INT NULL COMMENT '',
  PRIMARY KEY (`pageSectionId`) ,
  INDEX `fk_ictmPageSection_ictmPage1_idx` (`pageId` ASC) ,
  CONSTRAINT `fk_ictmPageSection_ictmPage1`
    FOREIGN KEY (`pageId`)
    REFERENCES `ictm`.`ictmPage` (`pageId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictm`.`ictmDepartment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictm`.`ictmDepartment` (
  `departmentId` INT NOT NULL COMMENT '' AUTO_INCREMENT,
  `departmentName` VARCHAR(255) NULL COMMENT '',
  `departmentHead` VARCHAR(100) NULL COMMENT '',
  `departmentSummary` MEDIUMTEXT NULL COMMENT '',
  `insertedBy` INT NULL COMMENT '',
  `insertedDate` DATETIME NULL COMMENT '',
  `lastModifiedBy` INT NULL COMMENT '',
  `lastModifiedDate` DATETIME NULL COMMENT '',
  `departmentStatus` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`departmentId`)  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictm`.`ictmCourse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictm`.`ictmCourse` (
  `courseId` INT NOT NULL COMMENT '' AUTO_INCREMENT,
  `departmentId` INT NOT NULL COMMENT '',
  `courseCodePearson` VARCHAR(100) NULL COMMENT '',
  `courseCodeIcon` VARCHAR(100) NULL COMMENT '',
  `ucasCode` VARCHAR(100) NULL COMMENT '',
  `courseTitle` VARCHAR(255) NOT NULL COMMENT '',
  `awardingTitle` VARCHAR(255) NULL COMMENT '',
  `awardingBody` VARCHAR(255) NULL COMMENT '',
  `accreditationType` VARCHAR(45) NULL COMMENT '',
  `accreditationNumber` VARCHAR(45) NULL COMMENT '',
  `courseDuration` INT NULL COMMENT '',
  `creditValue` INT NULL COMMENT '',
  `courseStructutre` VARCHAR(255) NULL COMMENT '',
  `studyMode` VARCHAR(100) NULL COMMENT '',
  `studyLanguage` VARCHAR(100) NULL COMMENT '',
  `academicYear` VARCHAR(100) NULL COMMENT '',
  `courseFees` INT NULL COMMENT '',
  `couseLocation` VARCHAR(100) NULL COMMENT '',
  `timeTable` VARCHAR(255) NULL COMMENT '',
  `courseStatus` VARCHAR(255) NULL COMMENT '',
  `courseImage` VARCHAR(255) NULL COMMENT '',
  `insertedBy` INT NULL COMMENT '',
  `insertedDate` DATETIME NULL COMMENT '',
  `lastModifiedBy` INT NULL COMMENT '',
  `lastModifiedDate` DATETIME NULL COMMENT '',
  PRIMARY KEY (`courseId`)  ,
  INDEX `fk_ictmCourse_ictmDepartment1_idx` (`departmentId` ASC)  ,
  CONSTRAINT `fk_ictmCourse_ictmDepartment1`
    FOREIGN KEY (`departmentId`)
    REFERENCES `ictm`.`ictmDepartment` (`departmentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictm`.`ictmRole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictm`.`ictmRole` (
  `roleId` INT NOT NULL COMMENT '' AUTO_INCREMENT,
  `roleName` VARCHAR(45) NULL COMMENT '',
  `roleDesc` VARCHAR(45) NULL COMMENT '',
  `insertedBy` INT NULL COMMENT '',
  `insertedDate` DATETIME NULL COMMENT '',
  `lastModifiedBy` INT NULL COMMENT '',
  `lastModifiedDate` DATETIME NULL COMMENT '',
  `roleStatus` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`roleId`)  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictm`.`ictmUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictm`.`ictmUsers` (
  `userId` INT NOT NULL COMMENT '' AUTO_INCREMENT,
  `roleId` INT NOT NULL COMMENT '',
  `userEmail` VARCHAR(100) NULL COMMENT '',
  `userPassword` VARCHAR(45) NULL COMMENT '',
  `userTitle` VARCHAR(45) NULL COMMENT '',
  `firstName` VARCHAR(100) NULL COMMENT '',
  `surName` VARCHAR(100) NULL COMMENT '',
  `jobTitle` VARCHAR(100) NULL COMMENT '',
  `insertedBy` INT NULL COMMENT '',
  `insertedDate` DATETIME NULL COMMENT '',
  `lastModifiedBy` INT NULL COMMENT '',
  `lastModifiedDate` DATETIME NULL COMMENT '',
  `usersStatus` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`userId`)  ,
  INDEX `fk_ictmUsers_ictmRole1_idx` (`roleId` ASC) ,
  CONSTRAINT `fk_ictmUsers_ictmRole1`
    FOREIGN KEY (`roleId`)
    REFERENCES `ictm`.`ictmRole` (`roleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictm`.`ictmEvent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictm`.`ictmEvent` (
  `eventId` INT NOT NULL COMMENT '' AUTO_INCREMENT,
  `eventTitle` VARCHAR(255) NULL COMMENT '',
  `eventDate` DATETIME NULL COMMENT '',
  `eventLocation` VARCHAR(45) NULL COMMENT '',
  `eventContent` MEDIUMTEXT NULL COMMENT '',
  `eventPhotoPath` VARCHAR(100) NULL COMMENT '',
  `eventType` VARCHAR(45) NULL COMMENT '',
  `insertedBy` INT NULL COMMENT '',
  `insertedDate` DATETIME NULL COMMENT '',
  `lastModifiedBy` INT NULL COMMENT '',
  `lastModifiedDate` DATETIME NULL COMMENT '',
  `eventStatus` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`eventId`)  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictm`.`ictmCourseSection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictm`.`ictmCourseSection` (
  `courseSectionId` INT NOT NULL COMMENT '' AUTO_INCREMENT,
  `courseId` INT NOT NULL COMMENT '',
  `courseSectionTitle` VARCHAR(255) NULL COMMENT '',
  `courseSectionContent` LONGTEXT NULL COMMENT '',
  `courseSectionImage` VARCHAR(255) NULL COMMENT '',
  `insertedBy` INT NULL COMMENT '',
  `insertedDate` DATETIME NULL COMMENT '',
  `lastModifiedBy` INT NULL COMMENT '',
  `lastModifiedDate` DATETIME NULL COMMENT '',
  `courseSectionStatus` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`courseSectionId`)  ,
  INDEX `fk_ictmCourseSection_ictmCourse1_idx` (`courseId` ASC)  ,
  CONSTRAINT `fk_ictmCourseSection_ictmCourse1`
    FOREIGN KEY (`courseId`)
    REFERENCES `ictm`.`ictmCourse` (`courseId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictm`.`ictmCourseUnits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictm`.`ictmCourseUnits` (
  `courseUnitd` INT NOT NULL COMMENT '' AUTO_INCREMENT,
  `courseId` INT NOT NULL COMMENT '',
  `unitNumber` INT NULL COMMENT '',
  `unitCode` VARCHAR(45) NULL COMMENT '',
  `unitName` VARCHAR(255) NULL COMMENT '',
  `unitCredit` INT NULL COMMENT '',
  `unitType` VARCHAR(45) NULL COMMENT '',
  `unitLevel` VARCHAR(45) NULL COMMENT '',
  `insertedBy` INT NULL COMMENT '',
  `insertedDate` DATETIME NULL COMMENT '',
  `lastModifiedBy` INT NULL COMMENT '',
  `lastModifieDate` DATETIME NULL COMMENT '',
  `courseUnitsStatus` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`courseUnitd`)  ,
  INDEX `fk_ictmCurseUnits_ictmCourse1_idx` (`courseId` ASC)  ,
  CONSTRAINT `fk_ictmCurseUnits_ictmCourse1`
    FOREIGN KEY (`courseId`)
    REFERENCES `ictm`.`ictmCourse` (`courseId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictm`.`ictmUnitSection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictm`.`ictmUnitSection` (
  `UnitSectionId` INT NOT NULL COMMENT ''AUTO_INCREMENT,
  `courseUnitd` INT NOT NULL COMMENT '',
  `UnitSectionTitle` VARCHAR(255) NULL COMMENT '',
  `UnitSectionContent` LONGTEXT NULL COMMENT '',
  `UnitSectionImage` VARCHAR(255) NULL COMMENT '',
  `insertedBy` INT NULL COMMENT '',
  `insertedDate` DATETIME NULL COMMENT '',
  `lastModifiedBy` INT NULL COMMENT '',
  `lastModifiedDate` DATETIME NULL COMMENT '',
  `unitSectionStatus` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`UnitSectionId`)  ,
  INDEX `fk_unitSection_ictmCurseUnits1_idx` (`courseUnitd` ASC)  ,
  CONSTRAINT `fk_unitSection_ictmCurseUnits1`
    FOREIGN KEY (`courseUnitd`)
    REFERENCES `ictm`.`ictmCourseUnits` (`courseUnitd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictm`.`ictmFaculty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictm`.`ictmFaculty` (
  `facultyId` INT NOT NULL COMMENT ''AUTO_INCREMENT,
  `facultyName` VARCHAR(100) NULL COMMENT '',
  `facultyDegree` VARCHAR(255) NULL COMMENT '',
  `facultyPosition` VARCHAR(255) NULL COMMENT '',
  `facultyEmpType` VARCHAR(100) NULL COMMENT '',
  `facultyEmail` VARCHAR(100) NULL COMMENT '',
  `faultyPhone` VARCHAR(45) NULL COMMENT '',
  `facultyTwitter` VARCHAR(100) NULL COMMENT '',
  `facultyLinkedIn` VARCHAR(255) NULL COMMENT '',
  `facultyIntro` MEDIUMTEXT NULL COMMENT '',
  `facultyImage` VARCHAR(255) NULL COMMENT '',
  `insertedBy` INT NULL COMMENT '',
  `insertedDate` DATETIME NULL COMMENT '',
  `lastModifiedBy` INT NULL COMMENT '',
  `lastModifiedDate` DATETIME NULL COMMENT '',
  `facultyStatus` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`facultyId`)  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictm`.`ictmFeedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictm`.`ictmFeedback` (
  `feedbackId` INT NOT NULL COMMENT '' AUTO_INCREMENT,
  `feedbackDetails` VARCHAR(100) NULL COMMENT '',
  `feedbackName` VARCHAR(45) NULL COMMENT '',
  `feedbackPhotePath` VARCHAR(100) NULL COMMENT '',
  `insertedBy` INT NULL COMMENT '',
  `insertedDate` DATETIME NULL COMMENT '',
  `lastModifiedBy` INT NULL COMMENT '',
  `lastModifiedDate` DATETIME NULL COMMENT '',
  `feedbackStatus` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`feedbackId`)  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictm`.`ictmNotices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictm`.`ictmNotices` (
  `noticeId` INT NOT NULL COMMENT '' AUTO_INCREMENT,
  `noticeTitle` VARCHAR(255) NULL COMMENT '',
  `noticeContent` MEDIUMTEXT NULL COMMENT '',
  `noticeDate` DATETIME NULL COMMENT '',
  `noticeType` VARCHAR(45) NULL COMMENT '',
  `insertedBy` INT NULL COMMENT '',
  `insertedDate` DATETIME NULL COMMENT '',
  `lastModifiedBy` INT NULL COMMENT '',
  `lastModifiedDate` DATETIME NULL COMMENT '',
  `noticeStatus` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`noticeId`)  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictm`.`ictmNews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictm`.`ictmNews` (
  `newstId` INT NOT NULL COMMENT '' AUTO_INCREMENT,
  `newsTitle` VARCHAR(255) NULL COMMENT '',
  `newsContent` MEDIUMTEXT NULL COMMENT '',
  `newsDate` DATETIME NULL COMMENT '',
  `newsType` VARCHAR(45) NULL COMMENT '',
  `insertedBy` INT NULL COMMENT '',
  `insertedDate` DATETIME NULL COMMENT '',
  `lastModifiedBy` INT NULL COMMENT '',
  `lastModifiedDate` DATETIME NULL COMMENT '',
  `newsStatus` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`newstId`)  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictm`.`ictmPhoto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictm`.`ictmPhoto` (
  `photoId` INT NOT NULL COMMENT '' AUTO_INCREMENT,
  `photoPath` VARCHAR(45) NULL COMMENT '',
  `photoName` VARCHAR(45) NULL COMMENT '',
  `photoDetails` LONGTEXT NULL COMMENT '',
  `insertedBy` VARCHAR(45) NULL COMMENT '',
  `insertedDate` DATETIME NULL COMMENT '',
  `lastModifiedBy` VARCHAR(45) NULL COMMENT '',
  `lastModifiedDate` DATETIME NULL COMMENT '',
  `photoStatus` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`photoId`)  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictm`.`ictmContactUs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictm`.`ictmContactUs` (
  `contactUsId` INT NOT NULL COMMENT '' AUTO_INCREMENT,
  `contactUsname` VARCHAR(45) NULL COMMENT '',
  `contactUsEmain` VARCHAR(100) NULL COMMENT '',
  `contactUsSubject` VARCHAR(255) NULL COMMENT '',
  `contactUsMessage` LONGTEXT NULL COMMENT '',
  `insertedBy` INT NULL COMMENT '',
  `insertedDate` DATETIME NULL COMMENT '',
  `lastModifiedBy` INT NULL COMMENT '',
  `lastModifiedDate` DATETIME NULL COMMENT '',
  `contactUsStatus` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`contactUsId`)  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictm`.`ictmCollegeInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictm`.`ictmCollegeInfo` (
  `collegeInfoId` INT NOT NULL COMMENT '' AUTO_INCREMENT,
  `collegeName` VARCHAR(45) NULL COMMENT '',
  `collegeDomain` VARCHAR(45) NULL COMMENT '',
  `collegeAddress` VARCHAR(45) NULL COMMENT '',
  `collegeTelephone1` VARCHAR(45) NULL COMMENT '',
  `collegeTelephone2` VARCHAR(45) NULL COMMENT '',
  `collegeFax` VARCHAR(255) NULL COMMENT '',
  `collegeFacebook` VARCHAR(255) NULL COMMENT '',
  `collegeTwitter` VARCHAR(45) NULL COMMENT '',
  `collegeLinkedIn` VARCHAR(45) NULL COMMENT '',
  `collegeGoogle` VARCHAR(45) NULL COMMENT '',
  `collegeYoutube` VARCHAR(45) NULL COMMENT '',
  `InsertedBy` INT NULL COMMENT '',
  `InsertedDate` VARCHAR(45) NULL COMMENT '',
  `lastModifiedBy` INT NULL COMMENT '',
  `lastModifiedDate` VARCHAR(45) NULL COMMENT '',
  `collegeInfoStatus` INT NULL COMMENT '',
  PRIMARY KEY (`collegeInfoId`)  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictm`.`ictmAffiliations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictm`.`ictmAffiliations` (
  `AffiliationsId` INT NOT NULL COMMENT '' AUTO_INCREMENT,
  `AffiliationsDetails` LONGTEXT NULL COMMENT '',
  `AffiliationsPhotoPath` VARCHAR(255) NULL COMMENT '',
  `InsertedBy` VARCHAR(255) NULL COMMENT '',
  `InsertedDate` DATETIME NULL COMMENT '',
  `lastModifiedBy` VARCHAR(255) NULL COMMENT '',
  `lastModifiedDate` DATETIME NULL COMMENT '',
  `affiliationsStatus` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`AffiliationsId`)  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictm`.`ictmHome`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictm`.`ictmHome` (
  `homeId` INT NOT NULL COMMENT '' AUTO_INCREMENT,
  `homeTitle` VARCHAR(100) NULL COMMENT '',
  `homeDetails` MEDIUMTEXT NULL COMMENT '',
  `homePhotoPath` VARCHAR(255) NULL COMMENT '',
  `insertedBy` INT NULL COMMENT '',
  `insertedDate` DATETIME NULL COMMENT '',
  `lastModifiedBy` INT NULL COMMENT '',
  `lastModifiedDate` DATETIME NULL COMMENT '',
  `homeStatus` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`homeId`)  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictm`.`ictmRegisterInterest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictm`.`ictmRegisterInterest` (
  `registerInterestId` INT NOT NULL COMMENT '' AUTO_INCREMENT,
  `firstName` VARCHAR(100) NULL COMMENT '',
  `surName` VARCHAR(100) NULL COMMENT '',
  `address` VARCHAR(255) NULL COMMENT '',
  `country` VARCHAR(100) NULL COMMENT '',
  `mobile` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(100) NULL COMMENT '',
  `session` VARCHAR(100) NULL COMMENT '',
  `course` VARCHAR(100) NULL COMMENT '',
  `hearAboutUs` VARCHAR(100) NULL COMMENT '',
  `other` VARCHAR(100) NULL COMMENT '',
  `disabilityRequire` VARCHAR(45) NULL COMMENT '',
  `appointmentDate` DATE NULL COMMENT '',
  `comments` VARCHAR(255) NULL COMMENT '',
  `inserDate` DATE NULL COMMENT '',
  PRIMARY KEY (`registerInterestId`)  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictm`.`ictmFacultyCourse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictm`.`ictmFacultyCourse` (
  `facultyCourseId` INT NOT NULL COMMENT '' AUTO_INCREMENT,
  `facultyId` INT NOT NULL COMMENT '',
  `courseId` INT NOT NULL COMMENT '',
  PRIMARY KEY (`facultyCourseId`)  ,
  INDEX `fk_ictmFacultyCourse_ictmFaculty1_idx` (`facultyId` ASC)  ,
  INDEX `fk_ictmFacultyCourse_ictmCourse1_idx` (`courseId` ASC)  ,
  CONSTRAINT `fk_ictmFacultyCourse_ictmFaculty1`
    FOREIGN KEY (`facultyId`)
    REFERENCES `ictm`.`ictmFaculty` (`facultyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ictmFacultyCourse_ictmCourse1`
    FOREIGN KEY (`courseId`)
    REFERENCES `ictm`.`ictmCourse` (`courseId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictm`.`ictmFacultyContact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictm`.`ictmFacultyContact` (
  `facultyContactId` INT NOT NULL COMMENT '' AUTO_INCREMENT,
  `facultyId` INT NOT NULL COMMENT '',
  `visitorName` VARCHAR(45) NULL COMMENT '',
  `visitorInterest` VARCHAR(45) NULL COMMENT '',
  `visitorEmail` VARCHAR(45) NULL COMMENT '',
  `visitorPhone` VARCHAR(45) NULL COMMENT '',
  `visitorEnquary` VARCHAR(45) NULL COMMENT '',
  `inserDate` DATE NULL COMMENT '',
  PRIMARY KEY (`facultyContactId`)  ,
  INDEX `fk_ictmFacultyContact_ictmFaculty1_idx` (`facultyId` ASC) ,
  CONSTRAINT `fk_ictmFacultyContact_ictmFaculty1`
    FOREIGN KEY (`facultyId`)
    REFERENCES `ictm`.`ictmFaculty` (`facultyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
